// Public-facing copy for the BAC and individualized support pathways.
// These pages make no claims of guaranteed efficacy or unverified certification.
export const care = {
  ru: {
    positioning: 'БАК и нейропсихологическая помощь детям и взрослым',
    intro: 'Вусала Касимова, нейропсихолог с опытом более 20 лет, принимает в Баку. Здесь можно пройти биоакустическую коррекцию (БАК) после первичной оценки. Работа также включает нейропсихологическую оценку и занятия, поддержку коммуникации и поведения, консультации для родителей.',
    book: 'Записаться на первичную консультацию', suitable: 'Узнать, подходит ли БАК в вашем случае', learn: 'Как проходит БАК',
    discuss: 'Обсудить ситуацию ребёнка', planTitle: 'Как строится индивидуальный план',
    planIntro: 'Состав помощи зависит от запроса и результатов оценки. Не каждому человеку нужны все направления, и БАК не назначается автоматически.',
    plan: [['Первичная консультация', 'Обсуждаем, что беспокоит в повседневной жизни, историю развития и уже полученную помощь.'], ['Нейропсихологическая оценка', 'Уточняем сильные стороны и трудности с учётом возраста, возможностей и утомляемости.'], ['Трудности и цели', 'Выбираем конкретные задачи, изменения в которых можно заметить и отслеживать.'], ['Индивидуальный план', 'Согласуем подходящие направления и рекомендации для дома. При необходимости подключаем других специалистов.'], ['Отслеживание динамики', 'Сравниваем наблюдения семьи и специалиста с исходной ситуацией.'], ['Корректировка плана', 'Пересматриваем задачи и нагрузку, обсуждаем продолжение или прекращение отдельных процедур.']],
    servicesTitle: 'Направления помощи', servicesIntro: 'В одном плане могут сочетаться разные направления. На консультации Вусала Касимова объяснит, какую задачу решает каждое из них.',
    components: [['Нейропсихологическая оценка', 'Исследование внимания, памяти и других когнитивных функций помогает выбрать задачи занятий. Медицинский диагноз требует соответствующего обследования.'], ['Нейропсихологическая коррекция', 'Задания подбираются под уровень развития и повседневные трудности. Работа может затрагивать обучение и когнитивную выносливость.'], ['Внимание и саморегуляция', 'Обсуждаем удержание задачи, планирование действий и переключение. Нагрузку соотносим с возможностями человека.'], ['Работа с родителями', 'Разбираем реальные ситуации дома и способы поддержки ребёнка между встречами.'], ['Взаимодействие со специалистами', 'При необходимости обсуждаем обращение к логопеду или врачу. Согласование рекомендаций с другими специалистами происходит с участием семьи.']],
    bac: {
      title: 'Биоакустическая коррекция (БАК) в Баку',
      description: 'БАК для детей и взрослых в Баку: как проходит сеанс, что обсудить до начала, БАК и РАС, СДВГ и трудности развития. Консультация Вусалы Касимовой.',
      lead: 'Интересует БАК для себя или ребёнка? Вусала Касимова поможет разобраться, какое место процедура может занять в индивидуальном плане помощи. Начните с консультации и оценки ситуации.',
      sections: [
        ['Что такое БАК', 'Биоакустическая коррекция использует запись электрической активности мозга: данные ЭЭГ преобразуются компьютером в звук в реальном времени. Человек слушает эти сигналы во время процедуры. Это описание технологии, а не доказательство лечебного результата.'],
        ['Как проходит сеанс', 'Специалист объясняет процедуру и размещает датчики на коже головы. Компьютер обрабатывает зарегистрированные сигналы ЭЭГ, а ребёнок или взрослый слушает полученный звук через наушники. До начала обсуждаются переносимость наушников и возможность спокойно участвовать в сеансе.'],
        ['Что происходит во время процедуры', 'Датчики регистрируют активность; в описанном методе они не подают электрический ток в мозг. Специалист наблюдает за состоянием человека. Если звук или датчики вызывают дискомфорт, об этом нужно сообщить: возможность паузы и прекращения обсуждают заранее. Прослушивание сигнала само по себе не означает «нормализацию мозга».'],
        ['С какими запросами обращаются', 'Родители спрашивают о БАК при трудностях внимания, гиперактивности или импульсивности, задержке развития, РАС, сложностях речи и коммуникации. Другие поводы обратиться: трудности обучения, памяти, поведения и эмоциональной саморегуляции. Взрослые могут обсудить когнитивную утомляемость и свои повседневные трудности. Эти запросы служат поводом для оценки, а не перечнем доказанных показаний к БАК.'],
        ['Как принимается решение о применении БАК', 'Сначала уточняются запрос и история развития или заболевания, изучаются имеющиеся заключения. Обсуждаются текущая помощь, цели и ограничения метода. Решение может включать БАК, другие занятия или направление к врачу до выбора процедуры. Диагноз сам по себе не определяет назначение курса.'],
        ['Почему перед началом нужна оценка', 'Похожие внешние трудности могут требовать разной помощи. Специалист оценивает навыки и нагрузку, уточняет сведения о здоровье и возможных противопоказаниях. Сообщите о приступах, принимаемых препаратах и реакции на звук. Вопросы медицинской безопасности решаются с врачом и с учётом инструкции к используемому оборудованию.'],
        ['Как БАК сочетается с другими направлениями', 'Если процедура включена в план, для неё заранее обсуждают цель и способ оценки изменений. Занятия по коммуникации, работа с поведением или нейропсихологическая коррекция выбираются по потребностям ребёнка. БАК не заменяет эти занятия и необходимую медицинскую помощь.']
      ],
      faq: [
        ['Можно ли применять БАК при РАС?', 'Семьи детей с РАС могут обратиться за консультацией о БАК. Это не означает, что БАК доказанно влияет на основные особенности аутизма. Решение обсуждается индивидуально; работа с коммуникацией, совместным взаимодействием и поведением сохраняет самостоятельное значение.'],
        ['БАК и СДВГ: с чего начать?', 'С оценки трудностей внимания и саморегуляции, а при подозрении на СДВГ также с диагностического обследования. Интерес к БАК не подтверждает его результативность при СДВГ. Процедура не должна подменять согласованную с лечащим специалистом помощь.'],
        ['БАК при задержке развития или речи запускает речь?', 'Мы не обещаем появления речи после определённого числа сеансов. Нужна оценка развития и коммуникации, при необходимости обследование слуха и консультация профильного специалиста. Поддержку подбирают под выявленные потребности.'],
        ['Подходит ли БАК при проблемах внимания?', 'Трудности внимания могут быть причиной обращения. На консультации оценивают контекст и выбирают направления работы; такой запрос сам по себе не доказывает пользу БАК.'],
        ['Сколько длится сеанс и сколько встреч нужно?', 'Длительность, возможный курс и стоимость уточняются до начала после оценки ситуации. На сайте нет единого числа сеансов для всех. Заранее согласуйте, когда и по каким наблюдениям будет пересматриваться план.'],
        ['Есть ли возрастные ограничения и противопоказания?', 'Возможность процедуры для конкретного ребёнка обсуждается с учётом возраста, состояния здоровья и инструкции к оборудованию. Не начинайте курс без обсуждения этих условий со специалистом.'],
        ['Можно ли гарантировать результат?', 'Нет. Нельзя обещать излечение аутизма или СДВГ, восстановление функций мозга либо определённый срок изменений. Изменения отслеживают по согласованным целям, учитывая остальные занятия и обстоятельства.'],
        ['Что взять на первую консультацию?', 'Имеющиеся заключения и результаты обследований, сведения о лекарствах и несколько примеров ситуаций, которые беспокоят. Обсудите опыт предыдущих занятий и ожидания от БАК.']
      ]
    },
    pages: {
      autism: {title: 'Помощь детям с РАС в Баку', description: 'Поддержка коммуникации, совместной игры и саморегуляции при РАС. Участие родителей, индивидуальные цели и обсуждение БАК с Вусалой Касимовой.', lead: 'Ребёнок редко включается в совместную игру, ему трудно показать, чего он хочет, или изменение распорядка вызывает сильную реакцию. На встрече можно разобрать именно эти ситуации.', sections: [
        ['Взаимодействие на уровне ребёнка', 'Работа может начинаться с короткой совместной игры по интересам ребёнка. Цели включают совместное внимание, отклик и инициативу в общении. Темп и способ взаимодействия подбираются под уровень развития; ребёнку помогают включаться без требования выглядеть или общаться определённым образом.'],
        ['Понимать и выражать потребности', 'Уточняем, как ребёнок просит нужное, отказывается или показывает, что ему тяжело. В работе используются понятные ему способы общения, в том числе жесты и визуальная поддержка по потребности. Обсуждаем, как взрослый замечает обращение и отвечает на него.'],
        ['Регуляция и сложные ситуации', 'Если ребёнку трудно пережить переход к другому занятию, разбираем, что происходило до реакции и после неё. Учитываются условия среды, доступность общения и возможный дискомфорт. Целью может стать понятный способ попросить паузу.'],
        ['Участие семьи', 'Родители помогают выбрать значимые бытовые задачи. На встречах обсуждаются совместная игра и поддержка взаимодействия дома. С согласия семьи рекомендации можно согласовать с детским садом или школой, чтобы ребёнок встречал понятные ему способы общения.'],
        ['БАК и аутизм', 'В практике доступна биоакустическая коррекция, и вопрос о ней можно обсудить на консультации. Интерес родителей к БАК не подтверждает его влияние на основные особенности РАС. План поддержки включает подходящие ребёнку социально-коммуникативные и поведенческие вмешательства независимо от решения о БАК.']
      ]},
      communication: {title: 'Развитие общения и социального взаимодействия', description: 'Социально-коммуникативная работа в Баку: совместное внимание и игра, выражение потребностей, участие родителей и перенос навыков в повседневную жизнь.', lead: 'Когда ребёнку трудно начать общение или поддержать игру, работа строится вокруг доступного ему взаимодействия и реальных ситуаций семьи.', sections: [
        ['Замечать друг друга', 'Совместное внимание означает возможность разделить интерес к предмету или событию. В игре можно поддерживать инициативу ребёнка и ответ на обращение взрослого, подбирая понятный способ привлечь его внимание.'],
        ['Просить, отвечать и отказываться', 'Цели могут включать понятную просьбу о помощи, выражение желания или отказ. Способ общения выбирается по возможностям ребёнка. При речевых трудностях обсуждается совместная работа с логопедом и другими профильными специалистами.'],
        ['Совместная игра', 'Чередование действий и короткие игровые эпизоды дают возможность практиковать взаимное общение. Понимание социальных сигналов связывается с конкретными ситуациями, без обещания освоить навык за установленный срок.'],
        ['Навыки за пределами кабинета', 'Вместе с родителями выбираются ежедневные ситуации для практики, например просьба о помощи во время одевания. Обсуждается, что ребёнок делает самостоятельно и какая подсказка ещё нужна. Наблюдения семьи помогают менять задачи.']
      ]},
      behaviour: {title: 'Работа с поведенческими трудностями', description: 'Поведенческая поддержка в Баку: причины и функции поведения, оценка ситуаций, измеримые цели и работа с родителями.', lead: 'Если ребёнок бросает задание, кричит или тяжело переносит переход к другому делу, сначала нужно понять ситуацию и потребность за этим поведением.', sections: [
        ['Что предшествует реакции', 'Трудности общения и невозможность выразить потребность могут влиять на поведение. Проверяем также шум и другие условия среды, слишком сложные требования, переходы между делами, усталость и изменения привычного распорядка. При подозрении на боль или сопутствующее заболевание нужна медицинская оценка.'],
        ['Функциональная оценка поведения', 'Вместе с родителями описываем конкретный эпизод: что произошло до него, что сделал ребёнок и что последовало дальше. Так можно выдвинуть и проверить предположение о функции поведения. Например, прекращение сложного задания после крика может закреплять этот способ просить перерыв. Это не означает, что ребёнок действует намеренно или что родители виноваты.'],
        ['Цели, которые можно проверить', 'Пример цели: научить ребёнка просить помощь или перерыв понятным способом. Другой пример: сократить количество ситуаций, в которых он бросает посильное задание при трудности. Сначала фиксируют исходные наблюдения, затем согласуют способ и срок оценки; числа выбираются индивидуально.'],
        ['Как строится поддержка', 'Обсуждаем посильную нагрузку и предсказуемые переходы, учим доступному способу общения, поддерживаем эмоциональную регуляцию. Родители пробуют согласованные способы в обычных ситуациях и сообщают, что происходит. План пересматривается по наблюдениям, с учётом безопасности и благополучия ребёнка.']
      ]}
    },
    related: 'Подробнее о поддержке', sources: 'Источники и границы информации', sourceNote: 'NICE CG170 описывает поддержку детей с РАС. Техническое описание БАК доступно у производителя оборудования.'
  },
  en: {
    positioning: 'BAC and neuropsychological support for children and adults',
    intro: 'Vusala Gasimova is a neuropsychologist with more than 20 years of experience, practising in Baku. The practice offers bioacoustic correction (BAC), starting with an individual assessment. The practice also offers neuropsychological assessment and intervention, communication and behavioural support, and guidance for parents.',
    book: 'Request an initial consultation', suitable: 'Find out whether BAC fits your situation', learn: 'How BAC sessions work', discuss: 'Discuss your child’s needs',
    planTitle: 'How an individual plan takes shape', planIntro: 'The combination of services depends on the assessment and your priorities. Each person receives selected components; BAC is not automatic.',
    plan: [['Initial consultation', 'Discuss everyday concerns, relevant history and support already received.'], ['Neuropsychological assessment', 'Explore strengths and difficulties at a pace suited to age, abilities and fatigue.'], ['Priorities and goals', 'Agree on specific everyday changes that can be observed and reviewed.'], ['Individual plan', 'Choose suitable services and home guidance, involving other professionals when needed.'], ['Progress review', 'Compare family and specialist observations with the starting point.'], ['Plan adjustment', 'Review goals and workload, including whether to continue or stop a procedure.']],
    servicesTitle: 'Areas of support', servicesIntro: 'Different services can be combined in one plan. Vusala Gasimova will explain the purpose of each proposed component.',
    components: [['Neuropsychological assessment', 'Assessment of attention, memory and other cognitive functions informs recommendations. A medical diagnosis requires the appropriate clinical evaluation.'], ['Neuropsychological intervention', 'Activities are matched to developmental level and daily difficulties, including learning and cognitive fatigue.'], ['Attention and self-regulation', 'Work may address staying with a task, planning and switching activities, with a manageable workload.'], ['Parent guidance', 'Discuss real situations at home and ways to support your child between appointments.'], ['Coordination with other specialists', 'Speech-language or medical referral is discussed when needed. Recommendations are coordinated with family involvement.']],
    bac: {title: 'Bioacoustic correction (BAC) in Baku', description: 'BAC for children and adults in Baku: the session, assessment before starting, questions about autism, ADHD and development. Consult Vusala Gasimova.', lead: 'Interested in BAC for yourself or your child? Vusala Gasimova can help you understand where the procedure might fit within an individual support plan. Begin with a consultation and assessment.', sections: [
      ['What is BAC?', 'Bioacoustic correction uses a recording of electrical brain activity. A computer converts EEG data into sound in real time, which the person listens to during the procedure. This describes the technology; it does not establish a clinical benefit.'],
      ['How a session works', 'The specialist explains the procedure and places sensors on the scalp. A computer processes the EEG signals and the child or adult listens to the resulting sound through headphones. Tolerance of headphones and the ability to participate comfortably are discussed beforehand.'],
      ['What happens during the procedure', 'The sensors record activity; in this method they do not deliver electrical current into the brain. The specialist observes the person’s comfort. Mention discomfort from the sound or sensors, and agree beforehand how to pause or stop. Hearing the signal does not in itself mean that brain function is being normalised.'],
      ['Concerns people bring to a consultation', 'Parents ask about BAC when a child has attention difficulties, hyperactivity or impulsivity, developmental delay, autism, or speech and communication difficulties. Learning, memory, behaviour and emotional regulation may also be concerns. Adults can discuss cognitive fatigue and everyday difficulties. These are reasons for assessment, not a list of proven BAC indications.'],
      ['How the decision is made', 'The first step is to discuss the concern, relevant history and available reports. Existing support, goals and the limitations of BAC are reviewed. The decision may involve BAC, other work or referral to a doctor before a procedure is considered. A diagnosis alone does not determine a course.'],
      ['Why assessment comes first', 'Similar visible difficulties may call for different forms of support. The specialist considers abilities, workload, health information and possible contraindications. Mention seizures, medication and sound sensitivity. Medical safety questions require a doctor’s input and the instructions for the equipment being used.'],
      ['Combining BAC with other support', 'If BAC is included, its proposed goal and the way changes will be reviewed are discussed beforehand. Communication work, behavioural support and neuropsychological intervention are selected according to individual needs. BAC does not replace these services or necessary medical care.']
    ], faq: [
      ['Can BAC be considered for an autistic child?', 'Families can ask about BAC in a consultation. Their interest does not establish that BAC improves the core features of autism. The decision is individual; communication, reciprocal interaction and behavioural support retain their own role.'],
      ['BAC and ADHD: where do we start?', 'Start with assessment of attention and self-regulation, including diagnostic evaluation when ADHD is suspected. Interest in BAC does not establish efficacy for ADHD. It should not replace care agreed with the treating clinician.'],
      ['Will BAC make a child with a speech or developmental delay speak?', 'We do not promise speech after a set number of sessions. Development and communication need assessment, with hearing evaluation or specialist referral when appropriate. Support follows the identified needs.'],
      ['Is BAC suitable for attention difficulties?', 'Attention difficulties are a reason to seek assessment. The context and suitable services are discussed; the concern alone does not establish a benefit from BAC.'],
      ['How long is a session and how many are needed?', 'Session length, a possible course and fees are clarified before starting, after assessment. There is no single number of sessions for everyone. Agree when the plan will be reviewed and what observations will inform that review.'],
      ['Are there age restrictions or contraindications?', 'Suitability for an individual child depends on age, health and the equipment instructions. Discuss these conditions with the specialist before starting a course.'],
      ['Is there a guaranteed result?', 'No. We cannot promise to cure autism or ADHD, restore brain function or produce change within a fixed time. Progress is reviewed against agreed goals while taking other support and circumstances into account.'],
      ['What should I bring to the first appointment?', 'Bring available reports, examination results and medication information, plus a few examples of situations that concern you. Discuss previous support and your expectations of BAC.']
    ]},
    pages: {
      autism: {title: 'Support for autistic children in Baku', description: 'Communication, shared play and self-regulation support for autistic children. Parent involvement, individual goals and questions about BAC.', lead: 'Your child rarely joins shared play, struggles to show what they need, or reacts strongly to a change of routine. The consultation can focus on those everyday situations.', sections: [
        ['Interaction at the child’s developmental level', 'Work can begin with brief shared play based on the child’s interests. Goals may include joint attention, responding and initiating interaction. Pace and communication are adapted to development, without requiring the child to look or communicate in a prescribed way.'],
        ['Understanding and expressing needs', 'Explore how the child asks, refuses or shows that something is difficult. Support uses accessible ways to communicate, including gestures or visual supports where needed. Discuss how adults notice and respond to attempts to interact.'],
        ['Regulation and difficult situations', 'When a transition is difficult, examine what happened before and after the reaction. Consider the environment, access to communication and possible discomfort. An accessible way to request a pause may be one goal.'],
        ['Family participation', 'Parents help choose meaningful everyday goals. Appointments can explore shared play and interaction at home. With the family’s agreement, guidance can be coordinated with nursery or school so familiar communication supports are available there too.'],
        ['BAC and autism', 'Bioacoustic correction is available in the practice and can be discussed in consultation. Parent interest does not establish an effect on the core features of autism. Suitable social-communication and behavioural interventions remain part of support planning regardless of the BAC decision.']
      ]},
      communication: {title: 'Social communication and interaction', description: 'Social-communication support in Baku: shared attention and play, expressing needs, parent participation and skills in everyday life.', lead: 'When a child struggles to initiate contact or sustain play, work focuses on accessible interaction in situations that matter to the family.', sections: [
        ['Noticing one another', 'Joint attention involves sharing an interest in an object or event. Play can support the child’s initiative and response to an adult, using ways of attracting attention that the child understands.'],
        ['Asking, responding and refusing', 'Goals may include a clear request for help, expressing a wish or refusing. Communication is matched to the child’s abilities. Speech-language input and other specialist support can be discussed when needed.'],
        ['Playing together', 'Taking turns and brief shared activities offer opportunities for reciprocal interaction. Understanding social signals is linked to concrete situations, without a promise to acquire skills within a fixed period.'],
        ['Skills outside the practice', 'Parents help choose everyday opportunities, such as asking for help while getting dressed. Discuss what the child does independently and what prompts are still needed. Family observations help adjust the goals.']
      ]},
      behaviour: {title: 'Support with behavioural difficulties', description: 'Behavioural support in Baku: understanding triggers and functions, assessing everyday situations, measurable goals and parent guidance.', lead: 'When a child abandons a task, shouts or struggles to move to a new activity, first explore the situation and the need behind the behaviour.', sections: [
        ['What happens before the reaction?', 'Communication difficulties or an inability to express a need can influence behaviour. Also consider noise and other environmental factors, excessive demands, transitions, fatigue and changes in routine. Possible pain or coexisting health issues call for medical assessment.'],
        ['Functional assessment of behaviour', 'Describe a specific episode with parents: what happened before, what the child did and what followed. This helps form and check a hypothesis about the function. For example, ending a difficult task after shouting can reinforce that way of requesting a break. This does not imply deliberate manipulation or blame parents.'],
        ['Goals that can be reviewed', 'A goal might be to teach an understandable way to request help or a break. Another might be fewer occasions of abandoning a manageable task when it gets difficult. Record a starting point, then agree the measures and review period individually.'],
        ['Building support', 'Discuss manageable demands and predictable transitions, teach an accessible way to communicate and support emotional regulation. Parents try agreed approaches in daily situations and share what happens. Observations guide revisions, with the child’s safety and wellbeing in mind.']
      ]}
    }, related: 'Explore support', sources: 'Sources and scope', sourceNote: 'NICE CG170 covers support for autistic children. The equipment manufacturer describes BAC technology.'
  }
};

care.az = {
  positioning: 'Uşaqlar və böyüklər üçün BAK və neyropsixoloji yardım',
  intro: '20 ildən artıq təcrübəsi olan neyropsixoloq Vüsalə Qasımova Bakıda qəbul edir. Burada ilkin qiymətləndirmədən sonra bioakustik korreksiya (BAK) keçmək mümkündür. İşə neyropsixoloji qiymətləndirmə və məşğələlər, ünsiyyət və davranış dəstəyi, valideyn konsultasiyaları da daxildir.',
  book: 'İlkin konsultasiyaya yazıl', suitable: 'BAK-ın sizin vəziyyətinizə uyğunluğunu öyrənin', learn: 'BAK seansı necə keçir', discuss: 'Uşağın vəziyyətini müzakirə edin',
  planTitle: 'Fərdi plan necə qurulur', planIntro: 'Dəstəyin tərkibi müraciətdən və qiymətləndirmənin nəticələrindən asılıdır. Hər insana bütün xidmətlər lazım deyil; BAK avtomatik təyin edilmir.',
  plan: [['İlkin konsultasiya', 'Gündəlik çətinlikləri, inkişaf tarixçəsini və əvvəlki dəstəyi müzakirə edirik.'], ['Neyropsixoloji qiymətləndirmə', 'Yaşı, imkanları və yorulmanı nəzərə alaraq güclü tərəfləri və çətinlikləri araşdırırıq.'], ['Prioritetlər və məqsədlər', 'Müşahidə edib izləmək mümkün olan konkret gündəlik məqsədləri seçirik.'], ['Fərdi plan', 'Uyğun istiqamətləri və ev üçün tövsiyələri razılaşdırırıq. Ehtiyac olduqda digər mütəxəssislərə yönləndiririk.'], ['Dinamikanın izlənməsi', 'Ailənin və mütəxəssisin müşahidələrini başlanğıc vəziyyətlə müqayisə edirik.'], ['Planın yenilənməsi', 'Məqsədləri və yükü nəzərdən keçirir, ayrı-ayrı prosedurların davamını və ya dayandırılmasını müzakirə edirik.']],
  servicesTitle: 'Dəstək istiqamətləri', servicesIntro: 'Bir planda müxtəlif istiqamətlər birləşə bilər. Vüsalə Qasımova təklif olunan hər istiqamətin məqsədini konsultasiyada izah edəcək.',
  components: [['Neyropsixoloji qiymətləndirmə', 'Diqqət, yaddaş və digər koqnitiv funksiyaların qiymətləndirilməsi tövsiyələrin seçilməsinə kömək edir. Tibbi diaqnoz müvafiq müayinə tələb edir.'], ['Neyropsixoloji korreksiya', 'Tapşırıqlar inkişaf səviyyəsinə və gündəlik çətinliklərə uyğunlaşdırılır. Öyrənmə və koqnitiv yorulma üzərində iş aparıla bilər.'], ['Diqqət və özünütənzimləmə', 'Tapşırığı davam etdirmək, planlaşdırmaq və fəaliyyətlər arasında keçid müzakirə edilir. Yük insanın imkanlarına uyğun seçilir.'], ['Valideynlərlə iş', 'Evdəki real vəziyyətləri və görüşlər arasında uşağa dəstək yollarını müzakirə edirik.'], ['Digər mütəxəssislərlə əməkdaşlıq', 'Ehtiyac olduqda loqopedə və ya həkimə müraciət müzakirə edilir. Tövsiyələr ailənin iştirakı ilə uzlaşdırılır.']],
  bac: {title: 'Bakıda bioakustik korreksiya (BAK)', description: 'Bakıda uşaqlar və böyüklər üçün BAK: seansın gedişi, ilkin qiymətləndirmə, autizm, DEHB və inkişafla bağlı suallar. Vüsalə Qasımovanın konsultasiyası.', lead: 'Özünüz və ya uşağınız üçün BAK ilə maraqlanırsınız? Vüsalə Qasımova prosedurun fərdi dəstək planında hansı yeri tuta biləcəyini müzakirə etməyə kömək edəcək. İlk addım konsultasiya və qiymətləndirmədir.', sections: [
    ['BAK nədir?', 'Bioakustik korreksiya beynin elektrik aktivliyinin qeydindən istifadə edir. Kompüter EEG məlumatlarını real vaxtda səsə çevirir və insan prosedur zamanı bu siqnalları dinləyir. Bu, texnologiyanın təsviridir; klinik nəticənin sübutu deyil.'],
    ['Seans necə keçir', 'Mütəxəssis proseduru izah edir və sensorları baş dərisinə yerləşdirir. Kompüter EEG siqnallarını emal edir, uşaq və ya böyük yaranan səsi qulaqcıqla dinləyir. Qulaqcığa dözümlülük və seansda rahat iştirak imkanı əvvəlcədən müzakirə olunur.'],
    ['Prosedur zamanı nə baş verir', 'Sensorlar aktivliyi qeyd edir; bu metodda onlar beyinə elektrik cərəyanı vermir. Mütəxəssis insanın vəziyyətini izləyir. Səs və ya sensorlar narahatlıq yaradırsa, bunu bildirin. Fasilə və dayandırma imkanını əvvəlcədən razılaşdırın. Siqnalı dinləmək özlüyündə beynin fəaliyyətinin normallaşması demək deyil.'],
    ['Hansı müraciətlərlə gəlirlər', 'Valideynlər diqqət çətinlikləri, hiperaktivlik və impulsivlik, inkişaf ləngiməsi, autizm, nitq və ünsiyyət çətinlikləri zamanı BAK haqqında soruşurlar. Öyrənmə, yaddaş, davranış və emosional tənzimləmə də müraciət səbəbi ola bilər. Böyüklər koqnitiv yorulma və gündəlik çətinlikləri müzakirə edə bilərlər. Bunlar qiymətləndirmə üçün səbəblərdir, BAK-ın sübut olunmuş göstərişlərinin siyahısı deyil.'],
    ['BAK haqqında qərar necə verilir', 'Əvvəlcə müraciət, inkişaf və ya xəstəlik tarixçəsi, mövcud rəylər öyrənilir. Cari dəstək, məqsədlər və metodun məhdudiyyətləri müzakirə edilir. Qərara BAK, başqa məşğələlər və ya prosedur seçilməzdən əvvəl həkimə yönləndirmə daxil ola bilər. Təkcə diaqnoz kurs təyin etmək üçün əsas deyil.'],
    ['İlkin qiymətləndirmə nə üçün lazımdır', 'Oxşar görünən çətinliklər fərqli dəstək tələb edə bilər. Mütəxəssis bacarıqları, yükü, sağlamlıq məlumatlarını və mümkün əks-göstərişləri nəzərə alır. Tutmalar, qəbul edilən dərmanlar və səsə həssaslıq barədə məlumat verin. Tibbi təhlükəsizlik məsələləri həkimlə və istifadə olunan avadanlığın təlimatına uyğun həll edilir.'],
    ['BAK digər istiqamətlərlə necə birləşir', 'BAK plana daxil edilirsə, onun məqsədi və dəyişikliklərin necə qiymətləndiriləcəyi əvvəlcədən danışılır. Ünsiyyət, davranış dəstəyi və neyropsixoloji korreksiya fərdi ehtiyaclara görə seçilir. BAK bu məşğələləri və zəruri tibbi yardımı əvəz etmir.']
  ], faq: [
    ['Autizm spektr pozuntusu zamanı BAK nəzərdən keçirilə bilərmi?', 'Ailələr BAK haqqında konsultasiyaya müraciət edə bilərlər. Bu maraq BAK-ın autizmin əsas xüsusiyyətlərinə təsirini sübut etmir. Qərar fərdidir; ünsiyyət, qarşılıqlı əlaqə və davranış dəstəyi ayrıca əhəmiyyət daşıyır.'],
    ['BAK və DEHB: nədən başlamaq lazımdır?', 'Diqqət və özünütənzimləmə çətinliklərinin qiymətləndirilməsindən, DEHB şübhəsi olduqda diaqnostik müayinədən. BAK-a maraq onun DEHB zamanı nəticəsini təsdiqləmir. Prosedur müalicə edən mütəxəssislə razılaşdırılmış yardımı əvəz etməməlidir.'],
    ['BAK inkişaf və ya nitq ləngiməsi olan uşağın danışmasını təmin edirmi?', 'Müəyyən sayda seansdan sonra nitqin yaranacağına söz vermirik. İnkişaf və ünsiyyət qiymətləndirilməli, ehtiyac olduqda eşitmə müayinəsi və profil mütəxəssisinin konsultasiyası aparılmalıdır. Dəstək müəyyən edilmiş ehtiyaclara uyğun seçilir.'],
    ['Diqqət çətinlikləri zamanı BAK uyğundurmu?', 'Diqqət çətinliyi qiymətləndirməyə müraciət üçün səbəbdir. Vəziyyət və uyğun istiqamətlər müzakirə edilir; müraciətin özü BAK-ın faydasını sübut etmir.'],
    ['Seans nə qədər çəkir və neçə görüş lazımdır?', 'Müddət, mümkün kurs və qiymət qiymətləndirmədən sonra, başlamazdan əvvəl dəqiqləşdirilir. Hamı üçün eyni seans sayı yoxdur. Planın nə vaxt və hansı müşahidələrə əsasən yenidən nəzərdən keçiriləcəyini razılaşdırın.'],
    ['Yaş məhdudiyyəti və əks-göstərişlər varmı?', 'Konkret uşaq üçün uyğunluq yaş, sağlamlıq və avadanlığın təlimatı nəzərə alınaraq müzakirə olunur. Kursdan əvvəl bu şərtləri mütəxəssislə dəqiqləşdirin.'],
    ['Nəticəyə zəmanət verilirmi?', 'Xeyr. Autizmi və ya DEHB-ni sağaltmaq, beyin funksiyalarını bərpa etmək və ya müəyyən müddətdə dəyişiklik yaratmaq vəd edilmir. Dinamika razılaşdırılmış məqsədlərə görə, digər məşğələlər və şərait nəzərə alınmaqla izlənir.'],
    ['İlk konsultasiyaya nə gətirmək lazımdır?', 'Mövcud rəyləri, müayinə nəticələrini və dərman məlumatlarını gətirin. Sizi narahat edən bir neçə gündəlik vəziyyəti, əvvəlki dəstək təcrübəsini və BAK-dan gözləntilərinizi müzakirə edin.']
  ]},
  pages: {
    autism: {title: 'Bakıda autizmli uşaqlara dəstək', description: 'Autizm zamanı ünsiyyət, birgə oyun və özünütənzimləmə dəstəyi. Valideyn iştirakı, fərdi məqsədlər və BAK haqqında konsultasiya.', lead: 'Uşaq birgə oyuna az qoşulur, istədiyini göstərməkdə çətinlik çəkir və ya gündəlik qaydanın dəyişməsinə güclü reaksiya verir. Görüşdə məhz bu vəziyyətləri müzakirə etmək olar.', sections: [
      ['Uşağın inkişaf səviyyəsinə uyğun əlaqə', 'İş uşağın marağına əsaslanan qısa birgə oyunla başlaya bilər. Məqsədlərə birgə diqqət, ünsiyyətə cavab və təşəbbüs daxildir. Temp və ünsiyyət inkişaf səviyyəsinə uyğunlaşdırılır; uşağın müəyyən formada görünməsi və ya ünsiyyət qurması tələb edilmir.'],
      ['Ehtiyacları anlamaq və ifadə etmək', 'Uşağın necə istədiyini, imtina etdiyini və çətinliyi göstərdiyini araşdırırıq. Ona anlaşıqlı ünsiyyət üsulları, ehtiyac olduqda jestlər və vizual dəstək istifadə olunur. Böyüyün müraciəti necə görüb cavablandırdığı müzakirə edilir.'],
      ['Tənzimləmə və çətin vəziyyətlər', 'Başqa fəaliyyətə keçid çətindirsə, reaksiyadan əvvəl və sonra nə baş verdiyini araşdırırıq. Mühit, ünsiyyət imkanı və narahatlıq nəzərə alınır. Məqsədlərdən biri fasiləni anlaşıqlı şəkildə istəmək ola bilər.'],
      ['Ailənin iştirakı', 'Valideynlər əhəmiyyətli gündəlik məqsədləri seçməyə kömək edir. Görüşlərdə evdə birgə oyun və əlaqənin dəstəklənməsi müzakirə olunur. Ailənin razılığı ilə tövsiyələr bağça və ya məktəblə uzlaşdırıla bilər.'],
      ['BAK və autizm', 'Praktikada bioakustik korreksiya mövcuddur və konsultasiyada bu barədə danışmaq olar. Valideyn marağı BAK-ın autizmin əsas xüsusiyyətlərinə təsirini təsdiqləmir. BAK barədə qərardan asılı olmayaraq, plana uşağa uyğun sosial-kommunikativ və davranış müdaxilələri daxil edilə bilər.']
    ]},
    communication: {title: 'Ünsiyyət və sosial qarşılıqlı əlaqənin inkişafı', description: 'Bakıda sosial-kommunikativ iş: birgə diqqət və oyun, ehtiyacların ifadəsi, valideyn iştirakı və bacarıqların gündəlik həyata keçirilməsi.', lead: 'Uşağa əlaqə başlatmaq və ya oyunu davam etdirmək çətin olduqda, iş ona əlçatan qarşılıqlı əlaqə və ailənin real vəziyyətləri ətrafında qurulur.', sections: [
      ['Bir-birini fərq etmək', 'Birgə diqqət əşyaya və ya hadisəyə marağı bölüşməkdir. Oyunda uşağın təşəbbüsünü və böyüyün müraciətinə cavabı ona anlaşıqlı üsulla dəstəkləmək olar.'],
      ['İstəmək, cavab vermək və imtina etmək', 'Məqsədlərə yardım istəmək, arzusunu bildirmək və ya imtina etmək daxil ola bilər. Ünsiyyət üsulu uşağın imkanlarına uyğun seçilir. Ehtiyac olduqda loqoped və digər mütəxəssislərlə iş müzakirə edilir.'],
      ['Birgə oyun', 'Növbələşmə və qısa oyun epizodları qarşılıqlı ünsiyyəti məşq etməyə imkan verir. Sosial siqnalların anlaşılması konkret vəziyyətlərlə əlaqələndirilir. Bacarığın müəyyən müddətdə yaranacağı vəd edilmir.'],
      ['Kabinetdən kənar bacarıqlar', 'Valideynlərlə gündəlik məşq imkanları seçilir: məsələn, geyinərkən kömək istəmək. Uşağın nəyi müstəqil etdiyi və harada ipucuna ehtiyac duyduğu müzakirə olunur. Ailənin müşahidələri məqsədləri yeniləməyə kömək edir.']
    ]},
    behaviour: {title: 'Davranış çətinlikləri ilə iş', description: 'Bakıda davranış dəstəyi: səbəb və funksiyaların anlaşılması, gündəlik vəziyyətlərin qiymətləndirilməsi, ölçülə bilən məqsədlər və valideynlərlə iş.', lead: 'Uşaq tapşırığı atırsa, qışqırırsa və ya başqa fəaliyyətə keçməkdə çətinlik çəkirsə, əvvəlcə vəziyyəti və davranışın arxasındakı ehtiyacı anlamaq lazımdır.', sections: [
      ['Reaksiyadan əvvəl nə baş verir', 'Ünsiyyət çətinliyi və ehtiyacını ifadə edə bilməmək davranışa təsir edə bilər. Səs-küy və digər mühit amilləri, ağır tələblər, keçidlər, yorğunluq və rejim dəyişiklikləri də nəzərə alınır. Ağrı və ya yanaşı xəstəlik şübhəsi tibbi qiymətləndirmə tələb edir.'],
      ['Davranışın funksional qiymətləndirilməsi', 'Valideynlərlə konkret epizodu təsvir edirik: əvvəl nə baş verdi, uşaq nə etdi, sonra nə oldu. Bu, davranışın funksiyası haqqında fərziyyə qurmağa və yoxlamağa kömək edir. Məsələn, qışqırıqdan sonra çətin tapşırığın bitməsi bu fasilə istəmə üsulunu möhkəmləndirə bilər. Bu, uşağın qəsdən hərəkət etdiyi və ya valideynin günahkar olduğu demək deyil.'],
      ['Yoxlanıla bilən məqsədlər', 'Məqsəd uşağa yardım və ya fasiləni anlaşıqlı üsulla istəməyi öyrətmək ola bilər. Digər nümunə: bacardığı tapşırığı çətinlik yarananda atdığı halların sayını azaltmaq. Əvvəl başlanğıc müşahidələr qeydə alınır, sonra ölçmə üsulu və qiymətləndirmə vaxtı fərdi razılaşdırılır.'],
      ['Dəstəyin qurulması', 'Uyğun yük və əvvəlcədən anlaşılan keçidlər müzakirə edilir, əlçatan ünsiyyət üsulu öyrədilir və emosional tənzimləmə dəstəklənir. Valideynlər razılaşdırılmış üsulları gündəlik şəraitdə sınayıb müşahidələrini bölüşürlər. Plan uşağın təhlükəsizliyi və rifahı nəzərə alınaraq yenilənir.']
    ]}
  }, related: 'Dəstək haqqında ətraflı', sources: 'Mənbələr və məlumatın sərhədləri', sourceNote: 'NICE CG170 autizmli uşaqlara dəstəyi təsvir edir. BAK texnologiyasının təsviri avadanlıq istehsalçısında mövcuddur.'
};

care.de = {
  positioning: 'BAK und neuropsychologische Unterstützung für Kinder und Erwachsene',
  intro: 'Vüsalə Qasımova ist Neuropsychologin mit mehr als 20 Jahren Erfahrung und praktiziert in Baku. Die Praxis bietet bioakustische Korrektur (BAK) nach individueller Einschätzung an. Die Praxis bietet auch neuropsychologische Einschätzung und Förderung, Unterstützung bei Kommunikation und Verhalten sowie Elternberatung.',
  book: 'Erstgespräch anfragen', suitable: 'Klären, ob BAK zu Ihrer Situation passt', learn: 'So läuft eine BAK-Sitzung ab', discuss: 'Die Situation Ihres Kindes besprechen',
  planTitle: 'So entsteht ein individueller Plan', planIntro: 'Die Auswahl richtet sich nach der Einschätzung und Ihren Anliegen. Nicht jeder Mensch benötigt alle Angebote; BAK wird nicht automatisch eingeplant.',
  plan: [['Erstgespräch', 'Alltagsfragen, Vorgeschichte und bisherige Unterstützung besprechen.'], ['Neuropsychologische Einschätzung', 'Stärken und Schwierigkeiten unter Berücksichtigung von Alter, Fähigkeiten und Ermüdung erfassen.'], ['Prioritäten und Ziele', 'Konkrete Veränderungen im Alltag vereinbaren, die beobachtet werden können.'], ['Individueller Plan', 'Geeignete Angebote und Anregungen für zu Hause auswählen. Bei Bedarf weitere Fachpersonen einbeziehen.'], ['Verlauf beobachten', 'Beobachtungen der Familie und der Fachperson mit der Ausgangslage vergleichen.'], ['Plan anpassen', 'Ziele und Belastung überprüfen, einschließlich Fortführung oder Beendigung einzelner Verfahren.']],
  servicesTitle: 'Unterstützungsangebote', servicesIntro: 'Verschiedene Angebote können in einem Plan zusammenkommen. Vüsalə Qasımova erläutert im Gespräch den Zweck jedes vorgeschlagenen Bestandteils.',
  components: [['Neuropsychologische Einschätzung', 'Die Erfassung von Aufmerksamkeit, Gedächtnis und weiteren kognitiven Funktionen hilft bei Empfehlungen. Eine medizinische Diagnose erfordert die entsprechende Untersuchung.'], ['Neuropsychologische Förderung', 'Aufgaben werden an Entwicklungsstand und Alltagsschwierigkeiten angepasst, etwa beim Lernen oder bei kognitiver Ermüdung.'], ['Aufmerksamkeit und Selbstregulation', 'Themen können das Weiterführen einer Aufgabe, Planung und Tätigkeitswechsel sein. Die Belastung wird an die Möglichkeiten angepasst.'], ['Elternberatung', 'Alltagssituationen und Unterstützung zwischen den Terminen gemeinsam besprechen.'], ['Zusammenarbeit mit Fachpersonen', 'Bei Bedarf wird eine logopädische oder ärztliche Abklärung besprochen. Empfehlungen werden unter Beteiligung der Familie abgestimmt.']],
  bac: {title: 'Bioakustische Korrektur (BAK) in Baku', description: 'BAK für Kinder und Erwachsene in Baku: Ablauf, Einschätzung vor Beginn und Fragen zu Autismus, ADHS und Entwicklung. Beratung bei Vüsalə Qasımova.', lead: 'Interessieren Sie sich für BAK für sich oder Ihr Kind? Vüsalə Qasımova bespricht mit Ihnen, welchen Platz das Verfahren in einem individuellen Unterstützungsplan einnehmen könnte. Am Anfang stehen Gespräch und Einschätzung.', sections: [
    ['Was ist BAK?', 'Bei der bioakustischen Korrektur wird elektrische Hirnaktivität aufgezeichnet. Ein Computer wandelt EEG-Daten in Echtzeit in Schall um, den die Person während des Verfahrens hört. Dies beschreibt die Technik und belegt keinen klinischen Nutzen.'],
    ['So läuft eine Sitzung ab', 'Die Fachperson erklärt den Ablauf und bringt Sensoren auf der Kopfhaut an. Ein Computer verarbeitet die EEG-Signale; das Kind oder die erwachsene Person hört den daraus erzeugten Klang über Kopfhörer. Vorher wird besprochen, ob Kopfhörer und Teilnahme gut toleriert werden.'],
    ['Was während des Verfahrens geschieht', 'Die Sensoren zeichnen Aktivität auf; bei diesem Verfahren leiten sie keinen elektrischen Strom ins Gehirn. Die Fachperson beobachtet das Befinden. Sprechen Sie Beschwerden durch Klang oder Sensoren an und vereinbaren Sie vorab Pausen und Abbruchmöglichkeiten. Das Hören des Signals bedeutet für sich genommen keine Normalisierung der Hirnfunktion.'],
    ['Mit welchen Anliegen Familien kommen', 'Eltern fragen nach BAK bei Aufmerksamkeitsproblemen, Hyperaktivität oder Impulsivität, Entwicklungsverzögerung, Autismus sowie Sprach- und Kommunikationsschwierigkeiten. Auch Lernen, Gedächtnis, Verhalten und Emotionsregulation können Anliegen sein. Erwachsene können kognitive Ermüdung und Alltagsprobleme besprechen. Dies sind Gründe für eine Einschätzung, keine Liste nachgewiesener BAK-Indikationen.'],
    ['Wie über BAK entschieden wird', 'Zunächst werden Anliegen, Vorgeschichte und vorhandene Befunde besprochen. Bisherige Unterstützung, Ziele und Grenzen des Verfahrens werden berücksichtigt. Die Entscheidung kann BAK, andere Angebote oder eine ärztliche Abklärung vor der Verfahrenswahl umfassen. Eine Diagnose allein bestimmt keinen Kurs.'],
    ['Warum eine Einschätzung vor Beginn nötig ist', 'Ähnlich aussehende Schwierigkeiten können unterschiedliche Unterstützung erfordern. Fähigkeiten, Belastung, Gesundheitsangaben und mögliche Kontraindikationen werden berücksichtigt. Informieren Sie über Anfälle, Medikamente und Geräuschempfindlichkeit. Fragen zur medizinischen Sicherheit gehören in ärztliche Hände und müssen die Geräteanleitung berücksichtigen.'],
    ['BAK mit anderen Angeboten verbinden', 'Wird BAK eingeplant, werden das vorgeschlagene Ziel und die Verlaufsbeobachtung vorher besprochen. Kommunikationsarbeit, Verhaltensunterstützung und neuropsychologische Förderung werden nach dem individuellen Bedarf gewählt. BAK ersetzt diese Angebote oder notwendige medizinische Versorgung nicht.']
  ], faq: [
    ['Kann BAK bei einem autistischen Kind erwogen werden?', 'Familien können sich zu BAK beraten lassen. Ihr Interesse belegt keine Wirkung auf die Kernmerkmale von Autismus. Die Entscheidung ist individuell; Kommunikation, wechselseitige Interaktion und Verhaltensunterstützung behalten ihren eigenen Stellenwert.'],
    ['BAK und ADHS: Womit beginnen?', 'Mit einer Einschätzung von Aufmerksamkeit und Selbstregulation sowie einer diagnostischen Abklärung bei ADHS-Verdacht. Interesse an BAK belegt keine Wirksamkeit bei ADHS. Das Verfahren darf die mit behandelnden Fachpersonen vereinbarte Versorgung nicht ersetzen.'],
    ['Bringt BAK ein Kind mit Sprach- oder Entwicklungsverzögerung zum Sprechen?', 'Wir versprechen keinen Sprachbeginn nach einer bestimmten Sitzungszahl. Entwicklung und Kommunikation müssen eingeschätzt werden, bei Bedarf auch das Hören und weitere fachliche Fragen. Die Unterstützung richtet sich nach dem festgestellten Bedarf.'],
    ['Eignet sich BAK bei Aufmerksamkeitsproblemen?', 'Aufmerksamkeitsprobleme können Anlass für eine Einschätzung sein. Kontext und geeignete Angebote werden besprochen; das Anliegen allein belegt keinen Nutzen von BAK.'],
    ['Wie lange dauert eine Sitzung und wie viele sind nötig?', 'Dauer, möglicher Kurs und Kosten werden nach der Einschätzung vor Beginn geklärt. Es gibt keine einheitliche Sitzungszahl für alle. Vereinbaren Sie, wann und anhand welcher Beobachtungen der Plan überprüft wird.'],
    ['Gibt es Altersgrenzen oder Kontraindikationen?', 'Die Eignung für ein Kind wird anhand von Alter, Gesundheit und Geräteanleitung besprochen. Klären Sie diese Bedingungen vor einem Kurs mit der Fachperson.'],
    ['Gibt es eine Erfolgsgarantie?', 'Nein. Eine Heilung von Autismus oder ADHS, die Wiederherstellung von Hirnfunktionen oder Veränderungen innerhalb einer festen Frist werden nicht versprochen. Der Verlauf wird anhand vereinbarter Ziele unter Berücksichtigung anderer Unterstützung und Umstände beobachtet.'],
    ['Was soll ich zum Erstgespräch mitbringen?', 'Vorhandene Befunde, Untersuchungsergebnisse und Medikamentenangaben sowie einige Beispiele belastender Alltagssituationen. Besprechen Sie bisherige Unterstützung und Ihre Erwartungen an BAK.']
  ]},
  pages: {
    autism: {title: 'Unterstützung für autistische Kinder in Baku', description: 'Kommunikation, gemeinsames Spiel und Selbstregulation bei Autismus. Elternbeteiligung, individuelle Ziele und Fragen zu BAK.', lead: 'Ihr Kind beteiligt sich selten am gemeinsamen Spiel, kann Bedürfnisse schwer zeigen oder reagiert stark auf eine geänderte Routine. Im Gespräch können genau diese Situationen im Mittelpunkt stehen.', sections: [
      ['Interaktion auf dem Entwicklungsniveau des Kindes', 'Die Arbeit kann mit kurzen gemeinsamen Spielen nach den Interessen des Kindes beginnen. Ziele umfassen geteilte Aufmerksamkeit, Reaktionen und eigene Kontaktaufnahme. Tempo und Kommunikation werden angepasst, ohne ein bestimmtes Aussehen oder Kommunikationsverhalten zu verlangen.'],
      ['Bedürfnisse verstehen und ausdrücken', 'Wir betrachten, wie das Kind bittet, ablehnt oder Schwierigkeiten zeigt. Verständliche Kommunikationswege, bei Bedarf Gesten oder visuelle Hilfen, werden genutzt. Besprochen wird auch, wie Erwachsene Kontaktversuche erkennen und darauf antworten.'],
      ['Regulation und schwierige Situationen', 'Ist ein Tätigkeitswechsel schwierig, betrachten wir die Ereignisse vor und nach der Reaktion. Umgebung, Kommunikationsmöglichkeiten und mögliches Unwohlsein werden berücksichtigt. Eine verständliche Bitte um Pause kann ein Ziel sein.'],
      ['Beteiligung der Familie', 'Eltern helfen, bedeutsame Alltagsziele auszuwählen. Gemeinsames Spiel und Interaktion zu Hause können besprochen werden. Mit Zustimmung der Familie lassen sich Empfehlungen mit Kita oder Schule abstimmen, damit vertraute Kommunikationshilfen dort verfügbar sind.'],
      ['BAK und Autismus', 'Bioakustische Korrektur wird in der Praxis angeboten und kann im Gespräch erörtert werden. Elterninteresse belegt keine Wirkung auf die Kernmerkmale von Autismus. Passende sozial-kommunikative und verhaltensbezogene Interventionen bleiben unabhängig von der BAK-Entscheidung Bestandteil der Unterstützungsplanung.']
    ]},
    communication: {title: 'Soziale Kommunikation und Interaktion', description: 'Sozial-kommunikative Unterstützung in Baku: geteilte Aufmerksamkeit, Spiel, Bedürfnisse ausdrücken und Fähigkeiten im Alltag mit Eltern üben.', lead: 'Wenn einem Kind Kontaktaufnahme oder gemeinsames Spiel schwerfallen, richtet sich die Arbeit nach zugänglicher Interaktion und den Alltagssituationen der Familie.', sections: [
      ['Einander wahrnehmen', 'Geteilte Aufmerksamkeit bedeutet, Interesse an einem Gegenstand oder Ereignis zu teilen. Im Spiel lassen sich die Initiative des Kindes und die Antwort auf Erwachsene mit verständlichen Zugängen unterstützen.'],
      ['Bitten, antworten und ablehnen', 'Ziele können eine klare Bitte um Hilfe, ein Wunsch oder eine Ablehnung sein. Der Kommunikationsweg wird an die Fähigkeiten angepasst. Bei Bedarf wird logopädische oder weitere fachliche Unterstützung besprochen.'],
      ['Gemeinsam spielen', 'Abwechselnde Handlungen und kurze gemeinsame Aktivitäten bieten Gelegenheiten für wechselseitigen Kontakt. Soziale Signale werden mit konkreten Situationen verbunden, ohne den Erwerb einer Fähigkeit innerhalb einer festen Frist zu versprechen.'],
      ['Fähigkeiten außerhalb der Praxis', 'Eltern helfen, tägliche Übungsmöglichkeiten zu wählen, etwa beim Anziehen um Hilfe zu bitten. Wir besprechen selbstständige Handlungen und noch nötige Hilfen. Beobachtungen der Familie unterstützen die Anpassung der Ziele.']
    ]},
    behaviour: {title: 'Unterstützung bei Verhaltensschwierigkeiten', description: 'Verhaltensunterstützung in Baku: Auslöser und Funktionen verstehen, Alltagssituationen einschätzen, messbare Ziele und Elternberatung.', lead: 'Wenn ein Kind Aufgaben abbricht, schreit oder einen Wechsel schwer bewältigt, werden zuerst die Situation und das Bedürfnis hinter dem Verhalten betrachtet.', sections: [
      ['Was der Reaktion vorausgeht', 'Kommunikationsschwierigkeiten und nicht ausdrückbare Bedürfnisse können Verhalten beeinflussen. Auch Lärm und andere Umweltfaktoren, zu hohe Anforderungen, Übergänge, Müdigkeit und Routineänderungen werden berücksichtigt. Bei möglichem Schmerz oder Begleiterkrankungen ist eine ärztliche Einschätzung nötig.'],
      ['Funktionale Verhaltensanalyse', 'Mit den Eltern beschreiben wir eine Episode: Was geschah vorher, was tat das Kind, was folgte? So lässt sich eine Vermutung zur Funktion entwickeln und überprüfen. Endet eine schwierige Aufgabe nach Schreien, kann dies diesen Weg zur Pause verstärken. Das unterstellt keine bewusste Manipulation und macht Eltern keine Vorwürfe.'],
      ['Überprüfbare Ziele', 'Ein Ziel kann sein, auf verständliche Weise um Hilfe oder eine Pause zu bitten. Ein anderes sind weniger Abbrüche einer bewältigbaren Aufgabe bei Schwierigkeiten. Zunächst wird die Ausgangslage festgehalten, danach werden Messung und Überprüfungszeitpunkt individuell vereinbart.'],
      ['Unterstützung gestalten', 'Angemessene Anforderungen und vorhersehbare Übergänge werden besprochen, zugängliche Kommunikation vermittelt und Emotionsregulation unterstützt. Eltern erproben vereinbarte Ansätze im Alltag und berichten darüber. Beobachtungen leiten Anpassungen unter Berücksichtigung von Sicherheit und Wohlbefinden des Kindes.']
    ]}
  }, related: 'Mehr zur Unterstützung', sources: 'Quellen und Geltungsbereich', sourceNote: 'NICE CG170 beschreibt die Unterstützung autistischer Kinder. Der Gerätehersteller erläutert die BAK-Technik.'
};
